name: ARM CPU compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ARM runner
      uses: pguyot/arm-runner-action@v2.5.2
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose --release
    - name: Upload binary artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: cconvert-arm-gnu
        path: target/release/cconvert
